spring.application.name=Jogos

# Configurações do banco de dados
spring.datasource.url=jdbc:mysql://localhost:3306/sedemdb
spring.datasource.username=root
spring.datasource.password=Id14340605@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA e Hibernate
# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Habilita execução de schema.sql ao iniciar
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

server.port=8086

# Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher